import './global.css';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import Container from '@/components/ui/Container';

export const metadata = {
  title: 'Welcome to team-master-front',
  description: 'Generated by create-nx-workspace',
  viewport: {
    width: 'device-width',
    initialScale: 1.0,
    maximumScale: 1.0,
    userScalable: 'no',
  },
  charset: 'utf-8',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <Container display="block" className="py-4 px-8">
          {children}
        </Container>
      </body>
    </html>
  );
}
